# Generated by Django 4.1.1 on 2022-09-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core1_model3',
            name='uploaded_at',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
